# Generated by Django 5.1.1 on 2024-09-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
