# Generated by Django 5.1.1 on 2024-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='name',
        ),
    ]
