# Generated by Django 5.1.1 on 2024-09-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_rename_content_tweet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='name',
            new_name='content',
        ),
    ]
